### ISSUE TITLE
Drawing over existing images is giving inconsistent result.

### ISSUE THREAD

**Issue by rhisss** [beck24/draw#1]
Drawing over existing images is giving inconsistent result.
Steps:
Opened a test Files page with approx 100 jpeg/jpgs
Edit File > Draw on one existing image
Drawing was okay
File saved was not seen in the file image page except broken icon in place of the jpeg
But changed file (existing file with drawing on it) was downloadable and viewable with changes

Went on to draw on another existing file
This time file was saved and seen with changes - everything okay
But this file was also seen in place of the previous file (described above) instead of the original file there

Cannot reproduce this error  always.

**Comment by rhisss** [comment]
Can reproduce this almost every time.
Draw on existing image. Save. Draw on yet one or two more images and save.
The previous images' thumbnails in listing and the actual images on the image pages are getting replaced by the last image on which "Draw" was applied.

You may see the changed/edited image apparently but refresh browser to see that it is not!

**Comment by beck24** [comment]
Try using the new version from master - I think this should have fixed it
