### ISSUE TITLE
Edit file > Draw on existing image does not show the overlay box

### ISSUE THREAD

**Issue by rhisss** [beck24/draw#2]
Instead it shows something like in a browser page
![untitled](https://cloud.githubusercontent.com/assets/3778500/5497366/d43b50ec-8736-11e4-881b-9419cdbd02ec.PNG)

Using FF - 34.0.5, Elgg 1.9.6
Maybe it has got something to do with the browser caching something extra. But by default user should not have to fiddle with browser to clean its cache.
In private mode of FF, logging in as the same user, I did not get this error.

**Comment by beck24** [comment]
sounds like you're getting javascript errors on the page which is preventing the launch of the lightbox.  Can you check firebug logs?

**Comment by rhisss** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3778500/5497704/4902a8aa-873a-11e4-904d-ffde85664632.PNG)

![untitled](https://cloud.githubusercontent.com/assets/3778500/5497743/cb1bfe18-873a-11e4-922c-8c2e6a2ba926.PNG)

**Comment by beck24** [comment]
Not on that page, the previous page where you click 'Draw a picture' - that's where the javascript is.  It's the lack of javascript (or broken js) that is sending you to a new page.  Broken js may not be an issue with this plugin though, it could be broken by any plugin that adds js to a page.

**Comment by rhisss** [comment]
I see, I will check  and report (but now the more problematic one is #1)

**Comment by rhisss** [comment]
I do not see any obvious js error - but it seems to happen when as mentioned in comment of #1

**Comment by beck24** [comment]
I still can't replicate this one though... all lightboxes are working correctly for me

**Comment by rhisss** [comment]
I think this problem is not there with the latest version.
